apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc3-frontend
  namespace: uc3-applications
  labels:
    app: uc3-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uc3-frontend
  template:
    metadata:
      labels:
        app: uc3-frontend
    spec:
      containers:
      - image: quay.io/bcapper30/uc3-apps:latest
        name: frontend
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: uc3-frontend-service
  namespace: uc3-applications
  labels:
    app: uc3-frontend
spec:
  selector:
    app: uc3-frontend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uc3-frontend-route
  namespace: uc3-applications
  labels:
    app: uc3-frontend
spec:
  to:
    kind: Service
    name: uc3-frontend-service
  port:
    targetPort: 8080
  tls:
    termination: edge 