apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucm-producer-deployment
  namespace: ${ApplicationName}
  labels:
    app: ucm-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucm-producer
  template:
    metadata:
      labels:
        app: ucm-producer
    spec:
      serviceAccountName: ${ServiceAccountName}
      volumes:
      - name: ucm-pv-storage
        persistentVolumeClaim:
          claimName: ${PersistentVolumeClaimName}
      containers:

      - image: ${Image}
        name: watcher-producer
        workingDir: ${VolumeMountPath}
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "watcher", "producer"]
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: JOB_SIZE
          value: "5"
        - name: AWS_ACCESS_KEY_ID
          value: "EEAAAAHuEn6LkwZJGpUAikGoJHyOrAra4yXAV1WVXpvA8XU0HAAAAAEB7vvNAAAAAAHu-80YrfBIAbZ4Ef4idjOF9BTQ"
        - name: AWS_SECRET_ACCESS_KEY
          value: "D3c2ApVsGGa7Wm1+pmfDwJddoPxhY3qSwU1U2EUUyKJRE07H3MjR3nwwaxim7mhY"
        - name: S3_ENDPOINT
          value: "https://s3.eu-central-1.ionoscloud.com"
        - name: S3_REGION
          value: "de"
        - name: S3_BUCKET_NAME
          value: "test-consumer"
        - name: EXPLORED_STARLIGHT
          value: "starlight/input"
        - name: EXPLORED_PPXF
          value: "ppxf/input"
        - name: EXPLORED_STECKMAP
          value: "steckmap/input"
        - name: PROCESSED_STARLIGHT
          value: "starlight/processed"
        - name: PROCESSED_PPXF
          value: "ppxf/processed"
        - name: PROCESSED_STECKMAP
          value: "steckmap/processed"
        - name: OUTPUT_STARLIGHT
          value: "starlight/output"
        - name: OUTPUT_PPXF
          value: "ppxf/output"
        - name: OUTPUT_STECKMAP
          value: "steckmap/output"
        - name: TEMPLATE_IN_FILE_PATH
          value: "/docker/starlight/config_files_starlight/grid_example.in"
        - name: "IN_FILE_OUTPUT_PATH"
          value: "${VolumeMountPath}starlight/runtime/infiles/"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        - name: METRICS
          value: "metrics/"
        ports:
        - containerPort: 5672
        volumeMounts:
        - mountPath: ${VolumeMountPath}
          name: ucm-pv-storage
        securityContext:
          privileged: ${SecurityContextPrivileged}

      - image: ${Image}
        name: http-server
        workingDir: ${VolumeMountPath}
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "server"]
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "EEAAAAHuEn6LkwZJGpUAikGoJHyOrAra4yXAV1WVXpvA8XU0HAAAAAEB7vvNAAAAAAHu-80YrfBIAbZ4Ef4idjOF9BTQ"
        - name: AWS_SECRET_ACCESS_KEY
          value: "D3c2ApVsGGa7Wm1+pmfDwJddoPxhY3qSwU1U2EUUyKJRE07H3MjR3nwwaxim7mhY"
        - name: S3_ENDPOINT
          value: "https://s3.eu-central-1.ionoscloud.com"
        - name: S3_REGION
          value: "de"
        - name: S3_BUCKET_NAME
          value: "test-consumer"
        - name: SERVER_PORT
          value: "8080"
        - name: CORS_ALLOWED_ORIGINS
          value: "*"
        - name: PROCESSED_STARLIGHT
          value: "starlight/processed"
        - name: PROCESSED_PPXF
          value: "ppxf/processed"
        - name: PROCESSED_STECKMAP
          value: "steckmap/processed"
        - name: OUTPUT_STARLIGHT
          value: "starlight/output"
        - name: OUTPUT_PPXF
          value: "ppxf/output"
        - name: OUTPUT_STECKMAP
          value: "steckmap/output"
        - name: EXPLORED_STARLIGHT
          value: "starlight/input"
        - name: EXPLORED_PPXF
          value: "ppxf/input"
        - name: EXPLORED_STECKMAP
          value: "steckmap/input"
        ports:
        - containerPort: ${ApiPort1}
        volumeMounts:
        - mountPath: ${VolumeMountPath}
          name: ucm-pv-storage
        securityContext:
          privileged: ${SecurityContextPrivileged}

      - image: ${Image}
        name: receiver-producer
        workingDir: ${VolumeMountPath}
        volumeMounts:
        - mountPath: ${VolumeMountPath}
          name: ucm-pv-storage
        securityContext:
          privileged: ${SecurityContextPrivileged}
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "consumer", "producer"]
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: AWS_ACCESS_KEY_ID
          value: "EEAAAAHuEn6LkwZJGpUAikGoJHyOrAra4yXAV1WVXpvA8XU0HAAAAAEB7vvNAAAAAAHu-80YrfBIAbZ4Ef4idjOF9BTQ"
        - name: AWS_SECRET_ACCESS_KEY
          value: "D3c2ApVsGGa7Wm1+pmfDwJddoPxhY3qSwU1U2EUUyKJRE07H3MjR3nwwaxim7mhY"
        - name: S3_ENDPOINT
          value: "https://s3.eu-central-1.ionoscloud.com"
        - name: S3_REGION
          value: "de"
        - name: S3_BUCKET_NAME
          value: "test-consumer"
        - name: IN_FILE_PATH
          value: "${VolumeMountPath}starlight/runtime/infiles"
        - name: PROCESS_LIST_STARLIGHT
          value: "${VolumeMountPath}starlight/runtime/processlist.txt" 
        - name: PROCESS_LIST_PPXF
          value: "${VolumeMountPath}ppxf/runtime/processlist.txt"
        - name: OUTPUT_BUCKET_STARLIGHT
          value: "starlight/output"
        - name: OUTPUT_BUCKET_PPXF
          value: "ppxf/output"
        - name: OUTPUT_BUCKET_STECKMAP
          value: "steckmap/output"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        - name: METRICS
          value: "metrics"

      - image: ${Image}
        name: aggregator
        workingDir: ${VolumeMountPath}
        ports:
        - containerPort: ${ApiPort2}
          protocol: TCP
          name: metrics
        volumeMounts:
        - mountPath: ${VolumeMountPath}
          name: ucm-pv-storage
        securityContext:
          privileged: ${SecurityContextPrivileged}
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "aggregator"]
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        - name: METRICS
          value: "metrics/"
        - name: AWS_ACCESS_KEY_ID
          value: "EEAAAAHuEn6LkwZJGpUAikGoJHyOrAra4yXAV1WVXpvA8XU0HAAAAAEB7vvNAAAAAAHu-80YrfBIAbZ4Ef4idjOF9BTQ"
        - name: AWS_SECRET_ACCESS_KEY
          value: "D3c2ApVsGGa7Wm1+pmfDwJddoPxhY3qSwU1U2EUUyKJRE07H3MjR3nwwaxim7mhY"
        - name: S3_ENDPOINT
          value: "https://s3.eu-central-1.ionoscloud.com"
        - name: S3_BUCKET_NAME
          value: "test-consumer"
        - name: S3_REGION
          value: "de"

---
  
apiVersion: v1
kind: Service
metadata:
  name: uc3-backend-service
  namespace: ${ApplicationName}
  labels:
    app: ucm-producer
    svc: ucm
spec:
  selector:
    app: ucm-producer
  ports:
  - name: api
    port: ${ApiPort1}
    targetPort: ${ApiPort1}
  - name: metrics
    port: ${ApiPort2}
    targetPort: ${ApiPort2}
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uc3-backend-api
  namespace: ${ApplicationName}
  labels:
    app: ucm-producer
spec:
  to:
    kind: Service
    name: uc3-backend-service
  port:
    targetPort: api
  tls:
    termination: edge 